### ISSUE TITLE
The code can not be run

### ISSUE THREAD

**Issue by Wang-Zheng-Jiu** [felrock/PyRacecarSimulator#2]
I build the package sucessfully,but there is not a executable documentation in devel/lib.Moreover, I can not roslaunch anything.

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 1 packages in topological order:
-- ~~  - PyRacecarSimulator
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'PyRacecarSimulator'
-- ==> add_subdirectory(PyracecarSimulator)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
WARNING: Package name "PyRacecarSimulator" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits, underscores, and dashes.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/wang/ROS/PyRacecarSimulator/build
####
####

(base) wang@wang-ROG-Strix-G531GW-S5DW:~/ROS/PyRacecarSimulator$ roslaunch PyRacecarSimulator simulate.launch
[simulate.launch] is neither a launch file in package [PyRacecarSimulator] nor is [PyRacecarSimulator] a launch file name
The traceback for the exception was written to the log file

**Comment by Wang-Zheng-Jiu** [comment]
Coul you please help me with that issue?Thank you a lot.

**Comment by felrock** [comment]
Hello, it seems that Ros does not acknowledge PyRacecarSimulator as a package. What does it say after you run catkin_make? Did you run compile.sh inside racecar? Do you have range_libc?
